# Generated by Django 4.0 on 2021-12-18 15:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_write'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
